#!/bin/bash

long_options="--mynym --hisnym" # long options

_opentxs_list_all_commands () # Get all opentxs commands from 'opentxs list'
{
# 	local i IFS=" "$'\n'
# 	for i in $(opentxs list 2>&1 /dev/null | sed -e '1,/Commands:/d') # start from 'Commands:' line
# 	do
# 		echo $i
# 	done
	local i IFS=" "$'\n'
	for i in $(./simplehint) # start from 'Commands:' line
	do
		echo $i
	done
}

# _opentxs_get_nyms () # Get all nyms from 'opentxs shownyms'
# {
# 	local i IFS=" "$'\n'
# 	for i in $(opentxs shownyms 2>&1 /dev/null | sed -e '1,/** PSEUDONYMS:/d' | cut -d \  -f 2) # start from '** PSEUDONYMS:' line
# 	do
# 		echo $i
# 	done
# }

_ot()
{
	local cur prev
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"

	case "${prev}" in
        sendmsg) # opentxs sendmsg
            local option="$long_options"
            COMPREPLY=( $(compgen -W "${option}" -- ${cur}) )
            return 0
            ;;
        --mynym)
            local option=$(_opentxs_get_nyms)
            COMPREPLY=( $(compgen -W "${option}" -- ${cur}) )
            return 0
            ;;
        *)
        ;;
	esac

	if [[ ${prev} == ot ]] ; then # if opentxs
		all_commands=$(_opentxs_list_all_commands)
		COMPREPLY=($(compgen -W "${all_commands}" -- ${cur}))
		return 0
	fi
}

complete -F _ot ot
